package render

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lathe-cli/lathe/internal/sourceconfig"
	"github.com/lathe-cli/lathe/internal/specsync"
	"github.com/lathe-cli/lathe/pkg/config"
	"github.com/lathe-cli/lathe/pkg/runtime"
)

type SkillModule struct {
	Source *sourceconfig.Source
	State  *specsync.State
	Specs  []runtime.CommandSpec
}

type moduleRef struct {
	Module SkillModule
	File   string
	Flat   bool
}

const skillOwnerFile = ".lathe-skill"

const (
	skillModuleReferenceSplitCommandThreshold = 100
	skillModuleReferenceSplitGroupThreshold   = 20
	skillModuleReferenceSplitSizeThreshold    = 64 * 1024
)

type SkillFileAction string

const (
	SkillFileAppend  SkillFileAction = "append"
	SkillFileCreate  SkillFileAction = "create"
	SkillFileReplace SkillFileAction = "replace"
	SkillFileOmit    SkillFileAction = "omit"
)

type SkillInclude struct {
	Path  string
	Files map[string]SkillFileAction
}

type skillFile struct {
	body []byte
	mode fs.FileMode
}

func RenderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule) error {
	return renderSkillDirectory(root, manifest, modules, SkillInclude{})
}

func RenderSkillDirectoryWithInclude(root string, manifest *config.Manifest, modules []SkillModule, include SkillInclude) error {
	return renderSkillDirectory(root, manifest, modules, include)
}

func renderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule, include SkillInclude) error {
	clean := filepath.Clean(root)
	if root == "" || clean == "." || clean == string(filepath.Separator) {
		return fmt.Errorf("invalid skill output directory %q", root)
	}
	if err := verifySkillDirectoryOwned(clean); err != nil {
		return err
	}
	include, err := normalizeSkillInclude(include)
	if err != nil {
		return err
	}
	if err := ValidateSkillIncludeRoot(filepath.Dir(clean), include.Path); err != nil {
		return err
	}
	allRefs, err := moduleReferences(manifest.CLI.CommandPath, modules)
	if err != nil {
		return err
	}
	allGenerated := renderSkillFiles(manifest, allRefs, nil)
	if err := validateSkillIncludePolicy(include, allGenerated); err != nil {
		return err
	}
	refs := filterOmittedModuleRefs(allRefs, include)
	files := renderSkillFiles(manifest, refs, omittedSkillFiles(include))
	if err := mergeSkillIncludes(files, allGenerated, include); err != nil {
		return err
	}
	if err := writeSkillDirectory(clean, files); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", clean, len(refs))
	return nil
}

func ValidateSkillIncludeRoot(skillRoot, includeRoot string) error {
	if includeRoot == "" {
		return nil
	}
	info, err := os.Stat(includeRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("skill include root %q does not exist", includeRoot)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill include root %q is not a directory", includeRoot)
	}
	if skillRoot == "" {
		return nil
	}
	absRoot, err := filepath.Abs(skillRoot)
	if err != nil {
		return err
	}
	absInclude, err := filepath.Abs(includeRoot)
	if err != nil {
		return err
	}
	if pathContains(absRoot, absInclude) || pathContains(absInclude, absRoot) {
		return fmt.Errorf("skill include root %q must be outside skill root %q", includeRoot, skillRoot)
	}
	return nil
}

func renderSkillFiles(manifest *config.Manifest, refs []moduleRef, omitted map[string]bool) map[string]skillFile {
	files := map[string]skillFile{
		"SKILL.md":              newSkillFile(renderSkillMD(manifest, refs)),
		skillOwnerFile:          newSkillFile("generated by lathe codegen; safe to remove and regenerate\n"),
		"agents/openai.yaml":    newSkillFile(renderOpenAIYAML(manifest)),
		"references/catalog.md": newSkillFile(renderCatalogReference(manifest)),
	}
	for _, ref := range refs {
		for rel, file := range renderModuleReferenceFiles(manifest, ref, omitted) {
			files[rel] = file
		}
	}
	return files
}

func newSkillFile(body string) skillFile {
	return skillFile{body: []byte(body), mode: 0o644}
}

func omittedSkillFiles(include SkillInclude) map[string]bool {
	if len(include.Files) == 0 {
		return nil
	}
	out := map[string]bool{}
	for rel, action := range include.Files {
		if action == SkillFileOmit {
			out[rel] = true
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func normalizeSkillInclude(include SkillInclude) (SkillInclude, error) {
	if len(include.Files) == 0 {
		return include, nil
	}
	out := SkillInclude{Path: include.Path, Files: map[string]SkillFileAction{}}
	for raw, action := range include.Files {
		rel, err := normalizeSkillRel(raw)
		if err != nil {
			return SkillInclude{}, err
		}
		if _, ok := out.Files[rel]; ok {
			return SkillInclude{}, fmt.Errorf("duplicate skill include policy for %q", rel)
		}
		out.Files[rel] = action
	}
	return out, nil
}

func normalizeSkillRel(rel string) (string, error) {
	clean := filepath.Clean(rel)
	slash := filepath.ToSlash(clean)
	if slash == "" || slash == "." || !filepath.IsLocal(clean) {
		return "", fmt.Errorf("invalid skill file path %q", rel)
	}
	if slash == skillOwnerFile {
		return "", fmt.Errorf("skill file %q is reserved", rel)
	}
	for _, part := range strings.Split(slash, "/") {
		if strings.HasPrefix(part, ".") {
			return "", fmt.Errorf("skill file path %q must not contain dotfile segments", rel)
		}
	}
	if _, err := defaultSkillFileAction(slash); err != nil {
		return "", err
	}
	return slash, nil
}

func defaultSkillFileAction(rel string) (SkillFileAction, error) {
	switch {
	case rel == "SKILL.md":
		return SkillFileAppend, nil
	case strings.HasPrefix(rel, "references/") && strings.HasSuffix(rel, ".md"):
		return SkillFileAppend, nil
	case strings.HasPrefix(rel, "agents/"),
		strings.HasPrefix(rel, "assets/"),
		strings.HasPrefix(rel, "references/"),
		strings.HasPrefix(rel, "scripts/"):
		return SkillFileCreate, nil
	default:
		return "", fmt.Errorf("skill include file %q must target SKILL.md, agents/, assets/, references/, or scripts/", rel)
	}
}

func validateSkillIncludePolicy(include SkillInclude, generated map[string]skillFile) error {
	for rel, action := range include.Files {
		switch action {
		case SkillFileReplace:
			if !canReplaceGeneratedSkillFile(rel) {
				return fmt.Errorf("skill include file %q cannot replace a generated Skill control file", rel)
			}
			if _, ok := generated[rel]; !ok {
				return fmt.Errorf("skill include file %q uses replace but no generated file exists at that path", rel)
			}
		case SkillFileOmit:
			if !canOmitGeneratedSkillFile(rel) {
				return fmt.Errorf("skill include file %q cannot be omitted", rel)
			}
			if _, ok := generated[rel]; !ok {
				return fmt.Errorf("skill include file %q uses omit but no generated file exists at that path", rel)
			}
		case SkillFileAppend:
			if !canAppendSkillFile(rel) {
				return fmt.Errorf("skill include file %q cannot be appended", rel)
			}
		case SkillFileCreate:
			if _, ok := generated[rel]; ok {
				return fmt.Errorf("skill include file %q uses create but a generated file already exists at that path", rel)
			}
		default:
			return fmt.Errorf("skill include file %q has invalid action %q", rel, action)
		}
	}
	return nil
}

func canAppendSkillFile(rel string) bool {
	return rel == "SKILL.md" || strings.HasPrefix(rel, "references/") && strings.HasSuffix(rel, ".md")
}

func canReplaceGeneratedSkillFile(rel string) bool {
	return rel == "SKILL.md" ||
		rel == "agents/openai.yaml" ||
		rel == "references/catalog.md" ||
		strings.HasPrefix(rel, "references/modules/") && strings.HasSuffix(rel, ".md")
}

func canOmitGeneratedSkillFile(rel string) bool {
	return rel == "agents/openai.yaml" ||
		strings.HasPrefix(rel, "references/modules/") && strings.HasSuffix(rel, ".md")
}

func filterOmittedModuleRefs(refs []moduleRef, include SkillInclude) []moduleRef {
	if len(include.Files) == 0 {
		return refs
	}
	out := refs[:0]
	for _, ref := range refs {
		if include.Files["references/modules/"+ref.File] == SkillFileOmit {
			continue
		}
		out = append(out, ref)
	}
	return out
}

func mergeSkillIncludes(files map[string]skillFile, generated map[string]skillFile, include SkillInclude) error {
	includeFiles, err := loadSkillIncludeFiles(include.Path)
	if err != nil {
		return err
	}
	covered := map[string]bool{}
	for rel, action := range include.Files {
		covered[rel] = true
		if err := applySkillIncludeAction(files, generated, includeFiles, rel, action); err != nil {
			return err
		}
	}
	for rel := range includeFiles {
		if covered[rel] {
			continue
		}
		action, err := defaultSkillFileAction(rel)
		if err != nil {
			return err
		}
		if err := applySkillIncludeAction(files, generated, includeFiles, rel, action); err != nil {
			return err
		}
	}
	return nil
}

func loadSkillIncludeFiles(includeRoot string) (map[string]skillFile, error) {
	out := map[string]skillFile{}
	if includeRoot == "" {
		return out, nil
	}
	if err := ValidateSkillIncludeRoot("", includeRoot); err != nil {
		return nil, err
	}
	err := filepath.WalkDir(includeRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		rawRel, err := filepath.Rel(includeRoot, path)
		if err != nil {
			return err
		}
		rel, err := normalizeSkillRel(rawRel)
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("skill include file %q is not a regular file", path)
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if _, ok := out[rel]; ok {
			return fmt.Errorf("duplicate skill include file %q", rel)
		}
		mode := fs.FileMode(0o644)
		if strings.HasPrefix(rel, "scripts/") && info.Mode().Perm()&0o111 != 0 {
			mode = 0o755
		}
		out[rel] = skillFile{body: body, mode: mode}
		return nil
	})
	return out, err
}

func applySkillIncludeAction(files map[string]skillFile, generated map[string]skillFile, includeFiles map[string]skillFile, rel string, action SkillFileAction) error {
	included, hasIncluded := includeFiles[rel]
	switch action {
	case SkillFileOmit:
		if hasIncluded {
			return fmt.Errorf("skill include file %q uses omit but an include file exists at that path", rel)
		}
		delete(files, rel)
		return nil
	case SkillFileReplace:
		if !hasIncluded {
			return fmt.Errorf("skill include file %q uses replace but no include file exists at that path", rel)
		}
		files[rel] = included
		return nil
	case SkillFileAppend:
		if !hasIncluded {
			return fmt.Errorf("skill include file %q uses append but no include file exists at that path", rel)
		}
		existing, ok := files[rel]
		if !ok {
			files[rel] = included
			return nil
		}
		merged := append([]byte(nil), existing.body...)
		if len(merged) > 0 && merged[len(merged)-1] != '\n' {
			merged = append(merged, '\n')
		}
		merged = append(merged, '\n')
		merged = append(merged, included.body...)
		files[rel] = skillFile{body: merged, mode: existing.mode}
		return nil
	case SkillFileCreate:
		if !hasIncluded {
			return fmt.Errorf("skill include file %q uses create but no include file exists at that path", rel)
		}
		if _, ok := generated[rel]; ok {
			return fmt.Errorf("skill include file %q targets an existing generated file", rel)
		}
		if _, ok := files[rel]; ok {
			return fmt.Errorf("skill include file %q targets an existing file", rel)
		}
		files[rel] = included
		return nil
	}
	return fmt.Errorf("skill include file %q has invalid action %q", rel, action)
}

func writeSkillDirectory(root string, files map[string]skillFile) error {
	parent := filepath.Dir(root)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}
	tmp, err := os.MkdirTemp(parent, "."+filepath.Base(root)+".tmp-")
	if err != nil {
		return err
	}
	removeTmp := true
	defer func() {
		if removeTmp {
			_ = os.RemoveAll(tmp)
		}
	}()
	for rel, file := range files {
		target := filepath.Join(tmp, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, file.body, file.mode); err != nil {
			return err
		}
	}
	if err := os.RemoveAll(root); err != nil {
		return err
	}
	if err := os.Rename(tmp, root); err != nil {
		return err
	}
	removeTmp = false
	return nil
}

func pathContains(base, path string) bool {
	rel, err := filepath.Rel(base, path)
	if err != nil {
		return false
	}
	return filepath.IsLocal(rel)
}

func verifySkillDirectoryOwned(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill output path %q exists and is not a directory", root)
	}
	if _, err := os.Stat(filepath.Join(root, skillOwnerFile)); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("refusing to remove existing non-lathe skill directory %q", root)
		}
		return err
	}
	return nil
}

func SkillDirName(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '-' || r == '_' || r == ' ' || r == '.':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "cli"
	}
	return out
}

func moduleReferences(policy string, modules []SkillModule) ([]moduleRef, error) {
	mods := append([]SkillModule(nil), modules...)
	sort.SliceStable(mods, func(i, j int) bool {
		return moduleName(mods[i]) < moduleName(mods[j])
	})
	used := map[string]int{}
	refs := make([]moduleRef, 0, len(mods))
	for _, mod := range mods {
		flat, err := ResolveFlatCommandPath(policy, len(mods), mod.Specs)
		if err != nil {
			return nil, err
		}
		base := SkillDirName(moduleName(mod))
		used[base]++
		fileBase := base
		if used[base] > 1 {
			fileBase = fmt.Sprintf("%s-%d", base, used[base])
		}
		refs = append(refs, moduleRef{Module: mod, File: fileBase + ".md", Flat: flat})
	}
	return refs, nil
}

type moduleGroupRef struct {
	Group string
	File  string
	Count int
}

func renderModuleReferenceFiles(manifest *config.Manifest, ref moduleRef, omitted map[string]bool) map[string]skillFile {
	moduleRel := "references/modules/" + ref.File
	if omitted[moduleRel] {
		return nil
	}
	rendered := renderModuleReference(manifest, ref.Module, ref.Flat)
	specs := visibleSpecs(ref.Module.Specs)
	groups := groupSpecs(specs)
	if !shouldSplitModuleReference(specs, groups, rendered) {
		return map[string]skillFile{moduleRel: newSkillFile(rendered)}
	}

	groupFiles := moduleGroupReferenceFiles(ref.File, groups)
	groupRefs := make([]moduleGroupRef, 0, len(groups))
	files := map[string]skillFile{}
	for _, group := range sortedKeys(groups) {
		groupFile := groupFiles[group]
		groupRel := "references/modules/" + groupFile
		if omitted[groupRel] {
			continue
		}
		groupRefs = append(groupRefs, moduleGroupRef{Group: group, File: groupFile, Count: len(groups[group])})
		files[groupRel] = newSkillFile(renderModuleGroupReference(manifest, ref.Module, group, groups[group], ref.Flat))
	}
	files[moduleRel] = newSkillFile(renderModuleIndexReference(manifest, ref.Module, groupRefs))
	return files
}

func shouldSplitModuleReference(specs []runtime.CommandSpec, groups map[string][]runtime.CommandSpec, rendered string) bool {
	if len(specs) == 0 {
		return false
	}
	return len(specs) > skillModuleReferenceSplitCommandThreshold ||
		len(groups) > skillModuleReferenceSplitGroupThreshold ||
		len(rendered) > skillModuleReferenceSplitSizeThreshold
}

func moduleGroupReferenceFiles(moduleFile string, groups map[string][]runtime.CommandSpec) map[string]string {
	moduleBase := strings.TrimSuffix(moduleFile, ".md")
	used := map[string]bool{}
	out := map[string]string{}
	for _, group := range sortedKeys(groups) {
		base := SkillDirName(group)
		for i := 2; used[base]; i++ {
			base = fmt.Sprintf("%s-%d", SkillDirName(group), i)
		}
		used[base] = true
		out[group] = moduleBase + "/" + base + ".md"
	}
	return out
}

func renderSkillMD(manifest *config.Manifest, refs []moduleRef) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: >\n  Use when operating the %s generated CLI. Discover commands, inspect parameters,\n  check auth state, and execute API operations safely.\n---\n\n", skill, cli)
	fmt.Fprintf(&b, "# %s CLI\n\n", cli)
	fmt.Fprintf(&b, "Use this skill when a user asks you to operate `%s`, inspect its API commands, or find the right generated command for an API task.\n\n", cli)
	b.WriteString("## Workflow\n\n")
	fmt.Fprintf(&b, "1. Search for candidates with `%s search \"<intent>\" --json`; use `--limit` when needed. Search is only candidate discovery.\n", cli)
	fmt.Fprintf(&b, "2. Inspect the exact command with `%s commands show <path...> --json` before executing an unfamiliar command.\n", cli)
	fmt.Fprintf(&b, "3. If the command detail has `auth.required=true`, run `%s auth status -o json` before execution and read `hostname` and `source`. Host resolution order: `--hostname` > `$%s` > the selected host (`%s auth use <host>`) > `http.default_hostname` > the single host in `hosts.yml`. If none applies, stop and ask the user to authenticate or select a host.\n", cli, manifest.CLI.HostEnv, cli)
	if len(manifest.Contexts) > 0 {
		fmt.Fprintf(&b, "4. If a flag has `context`, inspect `%s auth context status -o json`. Explicit flags override the declared environment variable, which overrides the value stored for the selected host.\n", cli)
		b.WriteString("5. Execute only after flags, body, auth, HTTP path, `mutation`, `dry_run`, and output hints are clear from `commands show`. When `mutation` is not `read`, preview with `--<dry_run.flag>` if `dry_run.mode` is `http_preview`; if preview is unavailable, obtain explicit user confirmation before execution.\n\n")
	} else {
		b.WriteString("4. Execute only after flags, body, auth, HTTP path, `mutation`, `dry_run`, and output hints are clear from `commands show`. When `mutation` is not `read`, preview with `--<dry_run.flag>` if `dry_run.mode` is `http_preview`; if preview is unavailable, obtain explicit user confirmation before execution.\n\n")
	}
	if manifest.Auth.Login != nil && manifest.Auth.Login.Type == config.AuthLoginOAuthDevice {
		b.WriteString("## Auth Login\n\n")
		fmt.Fprintf(&b, "- Use `%s auth login --device-auth --hostname <host> --provider <provider>` when the user needs browser-based OAuth login. The browser opens by default in an interactive terminal; use `--no-browser` for manual login.\n", cli)
		b.WriteString("- The saved host will use `auth_type: bearer`; OAuth is the login method, and the resulting API credential is a bearer token.\n\n")
	}
	b.WriteString("## General Commands\n\n")
	fmt.Fprintf(&b, "- `%s commands --json`: full generated command catalog.\n", cli)
	fmt.Fprintf(&b, "- `%s commands --include-hidden --json`: include hidden generated commands.\n", cli)
	fmt.Fprintf(&b, "- `%s commands show <path...> --json`: source of truth for one command.\n", cli)
	fmt.Fprintf(&b, "- `%s commands schema --json`: catalog schema version, surfaces, and dry-run result shape.\n", cli)
	fmt.Fprintf(&b, "- `%s search \"<intent>\" --json`: ranked candidate commands.\n", cli)
	fmt.Fprintf(&b, "- `%s auth status -o json`: resolved `hostname`, its `source`, the `selected` host, and every logged-in host.\n\n", cli)
	if len(manifest.Contexts) > 0 {
		fmt.Fprintf(&b, "- `%s auth context status -o json`: effective account-scoped context values for the selected host.\n\n", cli)
	}
	b.WriteString("## Maintenance Commands\n\n")
	fmt.Fprintf(&b, "- `%s --version` or `%s -v`: print CLI build version.\n", cli, cli)
	if manifest.Update.GitHub != nil {
		fmt.Fprintf(&b, "- `%s update`: update this CLI from configured GitHub Releases. Run only when the user explicitly asks to update `%s`; it may replace the current executable. Use `--yes` only when explicitly authorized.\n", cli, cli)
	}
	b.WriteString("\n")
	b.WriteString("## References\n\n")
	b.WriteString("- Read `references/catalog.md` for the command discovery protocol and catalog field meanings.\n")
	for _, ref := range refs {
		fmt.Fprintf(&b, "- Read `references/modules/%s` for the `%s` module command index; large modules may link to group detail files.\n", ref.File, moduleName(ref.Module))
	}
	b.WriteString("\n## Rules\n\n")
	b.WriteString("- Do not guess flags or request body shape from command names.\n")
	b.WriteString("- Do not execute directly from search results; confirm with `commands show` first.\n")
	b.WriteString("- When `mutation` is not `read`, preview before execution if `dry_run.mode` is `http_preview`. If preview is unavailable, obtain explicit user confirmation before execution. `unknown` is not safe to treat as read.\n")
	b.WriteString("- Prefer `-o json` for machine-readable command output unless the user asks for human-readable output.\n")
	b.WriteString("- With `-o json` or `-o yaml`, branch on `error.code` and process exit status; `error.message` and `error.hint` are safe human guidance, and `error.http.status` is the only optional HTTP context.\n")
	b.WriteString("- A configured stream pause is successful (`exit 0`); inspect the collected output field mapped from the pause event instead of treating it as an error.\n")
	b.WriteString("- For collected streams, choose one mode: `-o json` for one stable document, `--stream` in the default output mode when catalog `output.streaming.policy.live` is present, or `-o raw` for wire events.\n")
	b.WriteString("- Use `--file`, `--set`, or `--set-str` for JSON request bodies according to `commands show` body requirements.\n")
	b.WriteString("- When `body.runtime_schema` is present, normal execution fetches and validates against that schema before the target request; an `http_preview` dry-run stays network-free and skips this preflight.\n")
	b.WriteString("- For sensitive flags, prefer safe modes from `flags[].input_modes`: `--<flag>-env`, `--<flag>-file`, or `--<flag>-stdin`.\n")
	return b.String()
}

func renderOpenAIYAML(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	return fmt.Sprintf("interface:\n  display_name: %s\n  short_description: %s\n  default_prompt: %s\n",
		yamlString(cli+" CLI"),
		yamlString("Use the "+cli+" generated CLI"),
		yamlString("Use $"+skill+" to find and run the right "+cli+" command."),
	)
}

func renderCatalogReference(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	var b strings.Builder
	b.WriteString("# Catalog Protocol\n\n")
	b.WriteString("Use the runtime catalog as the source of truth. Generated references are a fast index; command execution details come from the CLI itself.\n\n")
	b.WriteString("## Search\n\n")
	fmt.Fprintf(&b, "Run `%s search \"<intent>\" --json` to find candidate commands. Use `--limit` to control result count. Treat search output as candidates only.\n\n", cli)
	b.WriteString("## Full Catalog\n\n")
	fmt.Fprintf(&b, "Run `%s commands --json` to inspect the generated command catalog. Use `--include-hidden` only when hidden commands are relevant.\n\n", cli)
	b.WriteString("Key fields:\n\n")
	b.WriteString("- `path`: command path to pass to `commands show` or execute after the CLI name.\n")
	b.WriteString("- `shortcuts`: root-level commands that execute the same operation with preset flag values.\n")
	b.WriteString("- `http`: HTTP method and path template.\n")
	fmt.Fprintf(&b, "- `http.default_hostname`: optional source-level host used after `--hostname`, `$%s`, and the host selected with `auth use`, and before the single-host fallback from `hosts.yml`.\n", manifest.CLI.HostEnv)
	b.WriteString("- `flags`: CLI flags, parameter location, type, required state, defaults, enum values, format, input modes, and help.\n")
	b.WriteString("- `body`: request body requirement, media type, and optional `runtime_schema` preflight source, including its active-context prerequisites.\n")
	b.WriteString("- `auth`: whether auth is required and which scopes are declared.\n")
	b.WriteString("- `mutation`: `read`, `write`, or `unknown`. Do not infer write vs read from the HTTP method alone. Treat any value other than `read` as requiring preview when `dry_run.mode` is `http_preview`, or explicit user confirmation when preview is unavailable.\n")
	b.WriteString("- `dry_run`: preview contract. `http_preview` is declared only when the generated runner can preview; use `--<flag>` and print the resolved HTTP request JSON. `unsupported` means the command has no preview, including all workflow commands. A `--dry-run` flag on a custom command is not a preview contract.\n")
	b.WriteString("- `examples`: runnable examples with optional body shape, output hints, and follow-up commands.\n")
	b.WriteString("- `output`: list path, default columns, response media type, pagination, and streaming hints; a streaming policy describes collection, terminal outcomes, and optional live projection.\n")
	b.WriteString("- `flags[].context`: an optional account-scoped default with explicit flag, declared environment, then stored-value precedence.\n")
	b.WriteString("- `sets_context`: a successful operation persists its declared parameter as the selected host's active context.\n")
	b.WriteString("- `notes`, `prerequisites`, and `known_errors`: overlay-provided operation context that is not inferred from the API spec.\n\n")
	b.WriteString("## Command Detail\n\n")
	fmt.Fprintf(&b, "Run `%s commands show <path...> --json` before executing an unfamiliar command. This is the source of truth for flags, body, auth, HTTP path, `mutation`, `dry_run`, and output hints.\n\n", cli)
	b.WriteString("## Schema\n\n")
	fmt.Fprintf(&b, "Run `%s commands schema --json` to read `catalog_schema_version`, `surfaces`, and `dry_run.result` before parsing catalog JSON with durable tooling. `dry_run.result=http_preview` means a preview prints the resolved HTTP request JSON (`method`, `url`, `hostname`, `host_source`, `headers`, `body`, `auth`, `output`).\n\n", cli)
	b.WriteString("## Sensitive Flags\n\n")
	b.WriteString("When a flag entry has `input_modes`, prefer safe modes over putting secrets directly in shell arguments.\n\n")
	b.WriteString("- `flag`: pass the direct `--<flag>` value; keep this for compatibility or non-secret values.\n")
	b.WriteString("- `env`: pass `--<flag>-env NAME` to read the value from an environment variable.\n")
	b.WriteString("- `file`: pass `--<flag>-file path` to read the value from a file.\n")
	b.WriteString("- `stdin`: pass `--<flag>-stdin` to read the value from stdin.\n")
	b.WriteString("- Use only one input mode for the same flag.\n\n")
	b.WriteString("## Request Bodies\n\n")
	b.WriteString("- `--file path`: read a JSON body from a file.\n")
	b.WriteString("- `--file -`: read a JSON body from stdin.\n")
	b.WriteString("- `--set key.path=value`: build JSON with type inference for booleans, null, integers, and floats.\n")
	b.WriteString("- `--set-str key.path=value`: build JSON while forcing the value to remain a string.\n\n")
	b.WriteString("If `body.runtime_schema` is present, normal execution fetches that JSON Schema and validates the body before the target request. An `http_preview` dry-run does not fetch it.\n\n")
	b.WriteString("## Output\n\n")
	b.WriteString("Use `-o json` for machine-readable command output. Other supported formats are `table`, `yaml`, and `raw`. For collected streams, choose one mode: JSON or YAML for one document, `--stream` in the default output mode when `output.streaming.policy.live` is present, or raw for wire events.\n\n")
	b.WriteString("On a non-zero exit with JSON or YAML output, read `error.code`, `error.message`, and `error.hint`; optional `error.http` contains only `status`. A configured pause exits zero and is represented by the field mapping in its stream collection policy.\n\n")
	b.WriteString("## Auth\n\n")
	fmt.Fprintf(&b, "If command detail returns `auth.required=true`, run `%s auth status -o json` before execution and read `hostname` and `source`. Host resolution order: `--hostname` > `$%s` > the selected host (`%s auth use <host>`) > `http.default_hostname` > the single host in `hosts.yml`. When more than one host is logged in and the host was chosen implicitly, the CLI also prints a `current host: <name>` line on stderr; read provenance from `auth status`, not from that line. If no matching host is logged in, stop and ask the user to authenticate.\n", cli, manifest.CLI.HostEnv, cli)
	if manifest.Auth.Login != nil && manifest.Auth.Login.Type == config.AuthLoginOAuthDevice {
		fmt.Fprintf(&b, "For browser-based OAuth login, run `%s auth login --device-auth --hostname <host> --provider <provider>`. The browser opens by default in an interactive terminal; use `--no-browser` for manual login. `auth_type: bearer` in `hosts.yml` is expected after login because API requests use the issued bearer token.\n", cli)
	}
	if len(manifest.Contexts) > 0 {
		fmt.Fprintf(&b, "Inspect effective account-scoped defaults with `%s auth context status -o json`; `local_set` reports whether `auth context set` is allowed. A command's explicit bound flag wins over its declared environment variable and stored host value.\n", cli)
	}
	return b.String()
}

func renderModuleReference(manifest *config.Manifest, mod SkillModule, flat bool) string {
	cli := manifest.CLI.Name
	specs := visibleSpecs(mod.Specs)
	var b strings.Builder
	fmt.Fprintf(&b, "# Module `%s`\n\n", moduleName(mod))
	writeModuleSource(&b, mod)
	if len(specs) == 0 {
		b.WriteString("No visible generated commands. Use `commands --include-hidden --json` if hidden commands are relevant.\n")
		return b.String()
	}
	groups := groupSpecs(specs)
	module := moduleName(mod)
	for _, group := range sortedKeys(groups) {
		writeModuleCommandGroup(&b, manifest, cli, module, group, groups[group], flat)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderModuleIndexReference(manifest *config.Manifest, mod SkillModule, groups []moduleGroupRef) string {
	cli := manifest.CLI.Name
	var b strings.Builder
	fmt.Fprintf(&b, "# Module `%s`\n\n", moduleName(mod))
	writeModuleSource(&b, mod)
	if len(groups) == 0 {
		b.WriteString("No visible generated commands. Use `commands --include-hidden --json` if hidden commands are relevant.\n")
		return b.String()
	}
	b.WriteString("## Command Groups\n\n")
	fmt.Fprintf(&b, "This module reference is split by command group. Read only the relevant group detail file, then inspect the exact command with `%s commands show <path...> --json` before execution.\n\n", cli)
	for _, group := range groups {
		fmt.Fprintf(&b, "- [%s](%s): %s\n", markdownLinkLabel(group.Group), group.File, commandCountLabel(group.Count))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderModuleGroupReference(manifest *config.Manifest, mod SkillModule, group string, specs []runtime.CommandSpec, flat bool) string {
	cli := manifest.CLI.Name
	module := moduleName(mod)
	var b strings.Builder
	fmt.Fprintf(&b, "# Module `%s`: %s\n\n", module, oneLine(group))
	fmt.Fprintf(&b, "Inspect exact command details with `%s commands show <path...> --json` before execution.\n\n", cli)
	writeModuleCommandGroup(&b, manifest, cli, module, group, specs, flat)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeModuleSource(b *strings.Builder, mod SkillModule) {
	b.WriteString("## Source\n\n")
	if mod.Source != nil {
		fmt.Fprintf(b, "- Backend: `%s`\n", mod.Source.Backend)
		if mod.Source.DefaultHostname != nil {
			fmt.Fprintf(b, "- Default hostname: `%s`\n", *mod.Source.DefaultHostname)
		}
		fmt.Fprintf(b, "- Repository: %s\n", valueOrUnknown(mod.Source.RepoURL))
		fmt.Fprintf(b, "- Pinned tag: `%s`\n", valueOrUnknown(mod.Source.PinnedTag))
		for _, line := range sourceInputs(mod.Source) {
			fmt.Fprintf(b, "- %s\n", line)
		}
	}
	if mod.State != nil && mod.State.ResolvedSHA != "" {
		fmt.Fprintf(b, "- Resolved SHA: `%s`\n", mod.State.ResolvedSHA)
	}
	b.WriteString("\n")
}

func writeModuleCommandGroup(b *strings.Builder, manifest *config.Manifest, cli, module, group string, specs []runtime.CommandSpec, flat bool) {
	fmt.Fprintf(b, "## %s\n\n", group)
	for _, spec := range specs {
		writeModuleCommand(b, manifest, cli, module, spec, flat)
	}
}

func writeModuleCommand(b *strings.Builder, manifest *config.Manifest, cli, module string, spec runtime.CommandSpec, flat bool) {
	path := commandPath(cli, module, spec, flat)
	fmt.Fprintf(b, "### `%s`\n\n", strings.Join(path, " "))
	if spec.Short != "" {
		fmt.Fprintf(b, "- Summary: %s\n", oneLine(spec.Short))
	}
	fmt.Fprintf(b, "- HTTP: `%s %s`\n", spec.Method, spec.PathTpl)
	fmt.Fprintf(b, "- Auth: %s\n", authSummary(spec.Security))
	fmt.Fprintf(b, "- Body: %s\n", bodySummary(spec.RequestBody))
	writeShortcuts(b, cli, spec)
	if len(spec.Params) == 0 {
		b.WriteString("- Flags: none\n")
	} else {
		b.WriteString("- Flags:\n")
		position := 0
		for _, p := range spec.Params {
			req := ""
			if p.Required {
				req = ", required"
			}
			def := ""
			if p.Default != "" {
				def = fmt.Sprintf(", default `%s`", p.Default)
			}
			format := ""
			if p.Format != "" {
				format = ", " + p.Format
			}
			enum := ""
			if len(p.Enum) > 0 {
				enum = ", one of: " + strings.Join(p.Enum, "|")
			}
			if len(p.ItemEnum) > 0 {
				enum = ", items one of: " + strings.Join(p.ItemEnum, "|")
			}
			deprecated := ""
			if p.Deprecated {
				deprecated = ", deprecated"
			}
			if p.Context != "" {
				info := manifest.Contexts[p.Context]
				contextSource := ", context `" + p.Context + "`"
				if info.Env != "" {
					contextSource += " via `" + info.Env + "`"
				}
				deprecated += contextSource
			}
			input := fmt.Sprintf("`--%s`", p.Flag)
			if p.Argument != "" {
				position++
				input = fmt.Sprintf("argument %d `[%s]` or `--%s`", position, p.Argument, p.Flag)
			}
			fmt.Fprintf(b, "  - %s (%s%s%s%s%s%s): %s\n", input, p.In, req, def, format, enum, deprecated, oneLine(stripHelpMeta(p.Help)))
		}

	}
	if out := outputSummary(spec.Output); out != "" {
		fmt.Fprintf(b, "- Output: %s\n", out)
	}
	writeOperationContext(b, spec)
	writeExamples(b, cli, module, spec, flat)
	b.WriteString("\n")
}

func writeShortcuts(b *strings.Builder, cli string, spec runtime.CommandSpec) {
	if len(spec.Shortcuts) == 0 {
		return
	}
	b.WriteString("- Shortcuts:\n")
	for _, shortcut := range spec.Shortcuts {
		preset := shortcutPreset(spec, shortcut)
		if preset == "" {
			fmt.Fprintf(b, "  - `%s %s`\n", cli, shortcut.Use)
			continue
		}
		fmt.Fprintf(b, "  - `%s %s` preset %s\n", cli, shortcut.Use, preset)
	}
}

func shortcutPreset(spec runtime.CommandSpec, shortcut runtime.CommandShortcut) string {
	if len(shortcut.Params) == 0 {
		return ""
	}
	flags := make(map[string]string, len(spec.Params)*2)
	for _, param := range spec.Params {
		flags[param.Name] = param.Flag
		flags[param.Flag] = param.Flag
	}
	keys := make([]string, 0, len(shortcut.Params))
	for key := range shortcut.Params {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		flag := flags[key]
		if flag == "" {
			flag = key
		}
		parts = append(parts, fmt.Sprintf("`--%s=%s`", flag, shortcut.Params[key]))
	}
	return strings.Join(parts, ", ")
}

func commandExample(example, cli, module string, spec runtime.CommandSpec, flat bool) string {
	newPath := strings.Join(commandPath(cli, module, spec, true), " ")
	oldPaths := []string{strings.Join(legacyCommandPath(cli, module, spec, flat), " ")}
	if !flat {
		newPath = strings.Join(commandPath(cli, module, spec, false), " ")
	} else {
		oldPaths = append([]string{
			strings.Join(commandPath(cli, module, spec, false), " "),
			strings.Join(legacyCommandPath(cli, module, spec, false), " "),
		}, oldPaths...)
	}
	for _, oldPath := range oldPaths {
		if oldPath != newPath {
			example = strings.ReplaceAll(example, oldPath, newPath)
		}
	}
	return example
}

func writeOperationContext(b *strings.Builder, spec runtime.CommandSpec) {
	writeStringList(b, "Notes", spec.Notes)
	writeStringList(b, "Prerequisites", spec.Prerequisites)
	if len(spec.SearchTerms) > 0 {
		terms := make([]string, 0, len(spec.SearchTerms))
		for _, term := range spec.SearchTerms {
			terms = append(terms, "`"+strings.ReplaceAll(oneLine(term), "`", "'")+"`")
		}
		fmt.Fprintf(b, "- Search terms: %s\n", strings.Join(terms, ", "))
	}
	if spec.SetContext != nil {
		param := spec.SetContext.Param
		if index, count := paramByNameOrFlag(spec.Params, param); count == 1 {
			param = spec.Params[index].Flag
		}
		fmt.Fprintf(b, "- Sets context `%s` from parameter `%s` after success.\n", spec.SetContext.Name, strings.ReplaceAll(oneLine(param), "`", "'"))
	}
	if len(spec.KnownErrors) == 0 {
		return
	}
	b.WriteString("- Known errors:\n")
	for _, err := range spec.KnownErrors {
		label := "unspecified status"
		if err.Status != 0 {
			label = fmt.Sprintf("HTTP %d", err.Status)
		}
		cause := oneLine(err.Cause)
		if cause == "" {
			fmt.Fprintf(b, "  - %s\n", label)
			continue
		}
		fmt.Fprintf(b, "  - %s: %s\n", label, cause)
	}
}

func writeStringList(b *strings.Builder, label string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "- %s:\n", label)
	for _, value := range values {
		fmt.Fprintf(b, "  - %s\n", oneLine(value))
	}
}

func writeExample(b *strings.Builder, example string) {
	text := strings.TrimRight(example, "\n")
	if strings.Contains(text, "\n") {
		fence := markdownFence(text)
		fmt.Fprintf(b, "- Example:\n\n%s\n%s\n%s\n", fence, text, fence)
		return
	}
	fmt.Fprintf(b, "- Example: `%s`\n", strings.ReplaceAll(oneLine(text), "`", "'"))
}

func writeExamples(b *strings.Builder, cli, module string, spec runtime.CommandSpec, flat bool) {
	examples := spec.Examples
	if len(examples) == 0 && spec.Example != "" {
		examples = []runtime.CommandExample{{Command: spec.Example}}
	}
	if len(examples) == 0 {
		return
	}
	if len(examples) == 1 {
		example := examples[0]
		if example.Summary == "" && example.Command != "" && len(example.BodyShape) == 0 && example.OutputHints == nil && len(example.FollowUpCommands) == 0 {
			writeExample(b, commandExample(example.Command, cli, module, spec, flat))
			return
		}
	}
	b.WriteString("- Examples:\n")
	for _, example := range examples {
		summary := oneLine(example.Summary)
		if summary == "" {
			summary = "Example"
		}
		fmt.Fprintf(b, "  - %s\n", summary)
		if example.Command != "" {
			fmt.Fprintf(b, "    Command: `%s`\n", strings.ReplaceAll(oneLine(commandExample(example.Command, cli, module, spec, flat)), "`", "'"))
		}
		if len(example.BodyShape) > 0 {
			fmt.Fprintf(b, "    Body shape: `%s`\n", strings.ReplaceAll(oneLine(string(example.BodyShape)), "`", "'"))
		}
		if example.OutputHints != nil {
			if example.OutputHints.IDPath != "" {
				fmt.Fprintf(b, "    Output ID path: `%s`\n", example.OutputHints.IDPath)
			}
			if example.OutputHints.ListPath != "" {
				fmt.Fprintf(b, "    Output list path: `%s`\n", example.OutputHints.ListPath)
			}
		}
		if len(example.FollowUpCommands) > 0 {
			b.WriteString("    Follow-up commands:\n")
			for _, command := range example.FollowUpCommands {
				fmt.Fprintf(b, "      - `%s`\n", strings.ReplaceAll(oneLine(commandExample(command, cli, module, spec, flat)), "`", "'"))
			}
		}
	}
}

func markdownFence(text string) string {
	fence := "```"
	for strings.Contains(text, fence) {
		fence += "`"
	}
	return fence
}

func visibleSpecs(specs []runtime.CommandSpec) []runtime.CommandSpec {
	out := make([]runtime.CommandSpec, 0, len(specs))
	for _, spec := range specs {
		if !spec.Hidden {
			out = append(out, spec)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Group == out[j].Group {
			return out[i].Use < out[j].Use
		}
		return out[i].Group < out[j].Group
	})
	return out
}

func groupSpecs(specs []runtime.CommandSpec) map[string][]runtime.CommandSpec {
	out := map[string][]runtime.CommandSpec{}
	for _, spec := range specs {
		group := spec.Group
		if group == "" {
			group = "Commands"
		}
		out[group] = append(out[group], spec)
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func moduleName(mod SkillModule) string {
	if mod.Source != nil && mod.Source.DisplayName != "" {
		return mod.Source.DisplayName
	}
	if mod.Source != nil && mod.Source.Name != "" {
		return mod.Source.Name
	}
	if mod.State != nil && mod.State.Source != "" {
		return mod.State.Source
	}
	return "module"
}

func sourceInputs(src *sourceconfig.Source) []string {
	switch src.Backend {
	case sourceconfig.BackendSwagger:
		return []string{"Files: `" + strings.Join(src.Swagger.Files, "`, `") + "`"}
	case sourceconfig.BackendOpenAPI3:
		return []string{"Files: `" + strings.Join(src.OpenAPI3.Files, "`, `") + "`"}
	case sourceconfig.BackendProto:
		lines := []string{"Entries: `" + strings.Join(src.Proto.Entries, "`, `") + "`"}
		if len(src.Proto.ImportRoots) > 0 {
			lines = append(lines, "Import roots: `"+strings.Join(src.Proto.ImportRoots, "`, `")+"`")
		}
		if len(src.Proto.Staging) > 0 {
			lines = append(lines, fmt.Sprintf("Staging entries: `%d`", len(src.Proto.Staging)))
		}
		return lines
	case sourceconfig.BackendGraphQL:
		if src.GraphQL == nil {
			return nil
		}
		lines := []string{"Schema: `" + src.GraphQL.Schema + "`"}
		if src.GraphQL.Expose != nil {
			if len(src.GraphQL.Expose.Queries) > 0 {
				lines = append(lines, "Expose queries: `"+strings.Join(src.GraphQL.Expose.Queries, "`, `")+"`")
			}
			if len(src.GraphQL.Expose.Mutations) > 0 {
				lines = append(lines, "Expose mutations: `"+strings.Join(src.GraphQL.Expose.Mutations, "`, `")+"`")
			}
		}
		if len(src.GraphQL.Groups) > 0 {
			lines = append(lines, fmt.Sprintf("Group policies: `%d`", len(src.GraphQL.Groups)))
		}
		if len(src.GraphQL.Output) > 0 {
			lines = append(lines, fmt.Sprintf("Output policies: `%d`", len(src.GraphQL.Output)))
		}
		if src.GraphQL.Selection != nil {
			parts := make([]string, 0, 2)
			if src.GraphQL.Selection.MaxDepth != nil {
				parts = append(parts, fmt.Sprintf("max depth `%d`", *src.GraphQL.Selection.MaxDepth))
			}
			if len(src.GraphQL.Selection.Prune) > 0 {
				parts = append(parts, fmt.Sprintf("prune rules `%d`", len(src.GraphQL.Selection.Prune)))
			}
			if len(parts) > 0 {
				lines = append(lines, "Selection policy: "+strings.Join(parts, "; "))
			}
		}
		return lines
	default:
		return nil
	}
}

func commandPath(cli, module string, spec runtime.CommandSpec, flat bool) []string {
	path := []string{cli}
	if !flat {
		path = append(path, module)
	}
	if group := rootCommandName(spec.Group); group != "" {
		path = append(path, group)
	}
	return append(path, spec.Use)
}

func legacyCommandPath(cli, module string, spec runtime.CommandSpec, flat bool) []string {
	path := []string{cli}
	if !flat {
		path = append(path, module)
	}
	if spec.Group != "" {
		path = append(path, strings.ToLower(spec.Group))
	}
	return append(path, spec.Use)
}

func authSummary(security *runtime.SecurityHint) string {
	if security != nil && security.Public {
		return "public"
	}
	if security != nil && len(security.Scopes) > 0 {
		return "required; scopes: `" + strings.Join(security.Scopes, "`, `") + "`"
	}
	return "required"
}

func bodySummary(body *runtime.RequestBody) string {
	if body == nil {
		return "none"
	}
	state := "optional"
	if body.Required {
		state = "required"
	}
	if body.Template != "" {
		merge := body.MergePath
		if merge == "" {
			merge = "the document root"
		}
		return state + "; templated body, set inputs under `" + merge + "` with --set/--set-str/--file"
	}
	if body.MediaType != "" {
		state += "; media type `" + body.MediaType + "`"
	}
	if body.RuntimeSchema != nil {
		state += "; runtime schema preflight"
	}
	return state
}

func outputSummary(out runtime.OutputHints) string {
	parts := make([]string, 0, 5)
	if out.ListPath != "" {
		parts = append(parts, "list path `"+out.ListPath+"`")
	}
	if len(out.DefaultColumns) > 0 {
		parts = append(parts, "columns `"+strings.Join(out.DefaultColumns, "`, `")+"`")
	}
	if out.ResponseMediaType != "" {
		parts = append(parts, "response media `"+out.ResponseMediaType+"`")
	}
	if out.Pagination != nil {
		parts = append(parts, "pagination `"+out.Pagination.Strategy+"`")
	}
	if out.Streaming != nil {
		streaming := "streaming `" + out.Streaming.Strategy + "`"
		if out.Streaming.Policy != nil {
			streaming += ", collected"
			if out.Streaming.Policy.Live != nil {
				streaming += ", live `--stream`"
			}
		}
		parts = append(parts, streaming)
	}
	return strings.Join(parts, "; ")
}

func commandCountLabel(count int) string {
	if count == 1 {
		return "1 command"
	}
	return fmt.Sprintf("%d commands", count)
}

func markdownLinkLabel(s string) string {
	out := oneLine(s)
	out = strings.ReplaceAll(out, `\`, `\\`)
	out = strings.ReplaceAll(out, "[", `\[`)
	out = strings.ReplaceAll(out, "]", `\]`)
	return out
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// stripHelpMeta removes the trailing " (...)" annotation that helpText() appends,
// so callers that render the metadata separately don't produce duplicates.
func stripHelpMeta(s string) string {
	if i := strings.LastIndex(s, " ("); i >= 0 && strings.HasSuffix(s, ")") {
		return s[:i]
	}
	return s
}

func valueOrUnknown(s string) string {
	if s == "" {
		return "`unknown`"
	}
	return s
}

func yamlString(s string) string {
	raw, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(raw)
}
